meta_product_name: "Studio Cariatide"
meta_title: "Studio Cariatide - Art — Design — Architecture"
meta_description: "Studio Cariatide est une agence parisienne regroupant de jeunes artistes émergents et confirmés."
meta_image: "meta.png"                           # Une image dans votre dossier app/assets/images/
